inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/migrate/**
    - db/schema.rb

# Generators use conventional triple-quote syntax, false positive
Lint/ImplicitStringConcatenation:
  Exclude:
    - 'lib/generators/browse_everything/*.rb'

Rails:
  Enabled: true

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 180
