language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=4.1.8"
    - "RAILS_VERSION=4.2.0"

matrix:
  include:
    - rvm: 1.9.3
      env: "RAILS_VERSION=4.1.8"
    - rvm: 2.0
      env: "RAILS_VERSION=4.1.8"

notifications:
  irc: "irc.freenode.org#projecthydra"

